# Geometry Constants
GALLON_PER_SEC = (1728/231)
DIAMETER_CUBED_DIVISOR = 6
DIAMETER_SQUARED_DIVISOR = 4
FEET_CUBED = "ft³"
FEET_SQUARED = "ft²"
FOOT_CUBED = 1728
FOOT_SQUARED = 144
GALLON_PER_MIN = GALLON_PER_SEC * 60
GALLON_PER_HOUR = GALLON_PER_MIN * 60
GALLON_PER_DAY = GALLON_PER_HOUR * 24
INCHES_CUBED = "in³"
INCHES_SQUARED = "in²"
ONE_FOOT = 12
